version: 4.0.0-aci-{build}

build_script:
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: dotnet build -c Release --version-suffix "aci-${env:APPVEYOR_BUILD_NUMBER}"
  - ps: dotnet test -c Release tests\Freya.Types.Http.Tests\Freya.Types.Http.Tests.fsproj
  - ps: dotnet test -c Release tests\Freya.Types.Http.Cors.Tests\Freya.Types.Http.Cors.Tests.fsproj
  - ps: dotnet test -c Release tests\Freya.Types.Http.State.Tests\Freya.Types.Http.State.Tests.fsproj
  - ps: dotnet test -c Release tests\Freya.Types.Language.Tests\Freya.Types.Language.Tests.fsproj
  - ps: dotnet test -c Release tests\Freya.Types.Uri.Tests\Freya.Types.Uri.Tests.fsproj
  - ps: dotnet test -c Release tests\Freya.Types.Uri.Template.Tests\Freya.Types.Uri.Template.Tests.fsproj
  - ps: dotnet pack -c Release --include-symbols --version-suffix "aci-${env:APPVEYOR_BUILD_NUMBER}"

test: off

artifacts:
  - path: '**\*.nupkg'
  - path: '**\BenchmarkDotNet.Artifacts\**\*.*'
